version: '3.9'
services:
  mysql:
    image: arm64v8/mysql
    container_name: sand-transport-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: bx9aaXX3W425RDF
      MYSQL_PASSWORD: bx9aaXX3W425RDF
      MYSQL_DATABASE: sand-transport
    volumes:
      - sand-transport-mysql-data:/var/lib/mysql
    networks:
      - sand-transport-net

volumes:
  sand-transport-mysql-data:
